defaults:
- config
- override model: hierarchical_s4
- override data_env: IntrinsicSlipEnv
- override model/hl_model@model.model.hl_model: mamba
- _self_

model:
  model:
    model_dim: 256
    dropout: 0.1
    freq_ratio: 10
    hl_model:
      _target_: hiss.models.MambaNet
      model_dim: ${model.model.model_dim}
      nlayers: 4
      ssm_cfg: null
      norm_epsilon: 1e-5
      rms_norm: false
      fused_add_norm: false
      residual_in_fp32: false
    ll_model:
      model_dim: 256
      nlayers: 6
      dropout: 0.1
      prenorm: true
