defaults:
- config
- override model: hierarchical_s4
- override data_env: JoystickControlEnv
- override model/hl_model@model.model.hl_model: mamba
- _self_

model:
  model:
    model_dim: 256
    dropout: 0.1
    hl_model:
      nlayers: 4
      rms_norm: false
      fused_add_norm: false
      residual_in_fp32: false
    ll_model:
      model_dim: 256
      nlayers: 4
      dropout: 0.1
      prenorm: true
