defaults:
  - hl_model@model.hl_model: s4
type: hierarchical_lstm
model:
  _target_: hiss.models.HierarchicalModel
  _partial_: true
  # hidden_dim: 32
  model_dim: 64
  dropout: 0.1
  freq_ratio: 10
  ll_model:
    _target_: hiss.models.LSTMNet
    _partial_: true
    hidden_dim: 64
    output_dim: ${model.model.model_dim}
    lstm_hidden_dim: 64
    nlayers: 1
    dropout: ${model.model.dropout}
