defaults:
  - hl_model@model.hl_model: s4
type: hierarchical_mamba
model:
  _target_: hiss.models.HierarchicalModel
  _partial_: true
  model_dim: 64
  dropout: 0.1
  freq_ratio: 10
  ll_model:
    _target_: hiss.models.MambaModel
    _partial_: true
    model_dim: 128
    output_dim: ${model.model.model_dim}
    nlayers: 1
    ssm_cfg: null
    norm_epsilon: 1e-5
    rms_norm: false
    fused_add_norm: false
    residual_in_fp32: false
